config/routes.rb
Rails.application.routes.draw do
	get 'welcome/index'
		resources :projects do
		resources :tasks
	end

root 'welcome#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord

	has_many :tasks, dependent: :destroy
	validates :title,:text, presence: true,
                    length: { minimum: 5 }
	validates :sdate,:edate, presence: true
	validate :date_validation


	private 
	def date_validation
		   if edate && sdate
      errors.add(:end_date, "can't be less than Start date") if edate < sdate
    end
  end
end

app/models/task.rb
class Task < ApplicationRecord
	belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
 		@projects = Project.all
	end

	def show
    		@project = Project.find(params[:id])
  	end

	def new
		@project = Project.new
	end
	
	def edit
		@project = Project.find(params[:id])
	end

	def create
  		@project = Project.new(project_params)
		  if @project.save
  			redirect_to @project
		else
			render 'new'
		end
	end

	def update
		@project = Project.find(params[:id])
			if @project.update(project_params)
				render 'show'
			else
				render 'edit'
			end	
	end

	def destroy
	    @project = Project.find(params[:id])
	    @project.destroy
	    redirect_to projects_path
  	end

		private
		  def project_params
		    params.require(:project).permit(:title, :text, :sdate, :edate)
		  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	def edit
	    @project = Project.find(params[:project_id])
	    @task = @project.tasks.find(params[:id])
	    @task.edit
	    redirect_to project_path(@project)
	end

	def create
	    @project = Project.find(params[:project_id])
	    @task = @project.tasks.create(tasks_params)
	    redirect_to project_path(@project)
	end



	def destroy
	    @project = Project.find(params[:project_id])
	    @task = @project.tasks.find(params[:id])
	    @task.destroy
	    redirect_to project_path(@project)
	end



	private
	    def tasks_params
	      params.require(:task).permit(:name, :description, :status, :employee)
	    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Prod1</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<div class="container">
	<%= form_with model: @project, url: projects_path, local: true do |form| %>
	  

	  <% if @project.errors.any? %>
	    <div id="error_explanation">
	      <h2>
	        <%= pluralize(@project.errors.count, "error") %> prohibited
	        this project from being saved:
	      </h2>
	      <ul>
	        <% @project.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	  <% end %>

		<p>
		    <%= form.label :project_name %><br>
		    <%= form.text_field :title %>
		</p>

		<p>
		    <%= form.label :project_summary %><br>
		    <%= form.text_area :text %>
		</p>

		<p>
		    <%= form.label :project_start_date %><br>
		    <%= form.date_field :sdate %><br>
		</p>

		<p>
		    <%= form.label :project_end_date %><br>
		    <%= form.date_field :edate %><br>
		</p>

		<p>
		    <%= form.submit %>
		</p>
	<% end %>
</div>

app/views/projects/edit.html.erb
<div class="container">
	<h1>Editing project</h1>
	<%= render 'form' %>
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table class="table">
  <tr>
    <th>Project title</th>
    <th>Project summary</th>
    <th>Start date</th>
    <th>End date</th>
    <th></th>
  </tr>

	<% @projects.each do |project| %>
	    <tr>
		    <td><%= project.title %></td>
		    <td><%= project.text %></td>
			<td><%= project.sdate %></td>
			<td><%= project.edate %></td>

		    <td><%= link_to 'Show', project_path(project) %></td>
		    <td><%= link_to 'Edit', edit_project_path(project) %></td>
			<td><%= link_to 'Delete', project_path(project),
		              method: :delete,
		              data: { confirm: 'Are you sure?' } %></td>
	    </tr>
	<% end %>

</table>

<button type="button" class="btn btn-link"><%= link_to 'Back', projects_path %></button>

<button type="button" class="btn btn-link"><%= link_to 'New Project', new_project_path %></button>

app/views/projects/new.html.erb
<div class="container">
	<h1>New project</h1>
	<%= render 'form' %>
	<%= link_to 'Back', projects_path %>
</div>

app/views/projects/show.html.erb
<div class="container">

	<p>
	  <strong>Project title:</strong>
	  <%= @project.title %>
	</p>

	<p>
	  <strong>Project summary:</strong>
	  <%= @project.text %>
	</p>

	<p>
	  <strong>Start date:</strong>
	  <%= @project.sdate %>
	</p>

	<p>
	  <strong>End date:</strong>
	  <%= @project.edate %>
	</p>


	<h2>Tasks</h2>
		<%= render @project.tasks %>

	
		<h2> Add task</h2>
			<%= render 'tasks/form' %>

	<button type="button" class="btn btn-link"><%= link_to 'Edit', edit_project_path(@project) %> </button>
	<button type="button" class="btn btn-link"><%= link_to 'Back', projects_path %></button>
</div>

app/views/tasks/_form.html.erb
<div class="form-group">
	<%= form_with(model: [ @project, @project.tasks.build ], local: true) do |form| %>

		<p>
			<%= form.label :task %><br>
			<%= form.text_field :name %>
		</p>
		<p>
			<%= form.label :description %><br>
			<%= form.text_area :description %>
		</p>

		<p>
			<%= form.radio_button :status, "New" %>
			<%= form.label :status, "New" %>
			<%= form.radio_button :status, "In progress" %>
			<%= form.label :status , "In progress" %>
			<%= form.radio_button :status, "Done" %>
			<%= form.label :status, "Done" %>
		</p>

		
		<p>
			<%= form.label :employee %><br>
			<%= form.text_area :employee %>
		</p>

		<p>
		    <%= form.submit %>
		</p>
			
	<% end %>
</div>

app/views/tasks/_task.html.erb
<table class="table">
	<p>
	    <strong>Task name:</strong>
	    <%= task.name %>
	</p>

	<p>
	    <strong>Task description:</strong>
	    <%= task.description %>
	</p>

	<p>
	    <strong>Task status:</strong>
	    <%= task.status %>
	</p>

	<p>
	    <strong>Appointed employees:</strong>
	    <%= task.employee %>
	</p>

	<%= link_to 'Delete Task', [task.project, task], method: :delete, data: {confirm: 'Are you sure?'} %><br>

	<%= link_to 'Edit Task', [task.project, task], method: :edit %>
</table>

app/views/welcome/index.html.erb
<h1>Hello, Rails!</h1>

<%= link_to 'My Projects', controller: 'projects' %>